Use correct domain root-servers.net for DNS probes
nmstate/kubernetes-nmstate pull request #1163
Opened 2023-04-03 10:15 UTC by andreaskaris

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

Closes https://github.com/nmstate/kubernetes-nmstate/issues/1164

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:
NONE

```release-note
NONE
```

----------------

Fix for https://issues.redhat.com/browse/OCPBUGS-11272

At time of this writing (both in OpenShift QE and from my laptop) we can see that root-server.net returns nothing:
~~~
[akaris@linux test]$ cat main.go
// You can edit this code!
// Click here and start typing.
package main

import (
"fmt"
"net"
)

func main() {
for _, i := range []string{"[www.google.com](http://www.google.com/)", "a.root-servers.net", "root-servers.net", "root-server.net"} {
ns, err := net.LookupNS(i)
fmt.Println(i, "ns", ns, "err", err)
}
}
[akaris@linux test]$ go run .
[www.google.com](http://www.google.com/) ns [] err lookup www.google.com on 127.0.0.53:53: no such host
a.root-servers.net ns [] err lookup a.root-servers.net on 127.0.0.53:53: no such host
root-servers.net ns [0xc000180200 0xc000180210 0xc000180230 0xc000180240 0xc000180250 0xc000180260 0xc000180270 0xc000180280 0xc000180290 0xc0001802a0 0xc0001802b0 0xc0001802c0 0xc0001802d0] err
root-server.net ns [] err lookup root-server.net on 127.0.0.53:53: no such host
[akaris@linux test]$
~~~

The correct domain is root-servers.net (plural) anyway: https://www.iana.org/domains/root/servers

2023-04-03 20:36 UTC, k8scoder192 commented
Why do I get Can't find root-servers.net (same for root-server.net). 
```
nslookup root-servers.net 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
*** Can't find root-servers.net: No answer
```

2023-04-04 10:14 UTC, qinqon commented
/retest

2023-04-04 10:17 UTC, qinqon commented
> Why do I get Can't find root-servers.net (same for root-server.net).
> 
> ```
> nslookup root-servers.net 8.8.8.8
> Server:         8.8.8.8
> Address:        8.8.8.8#53
> 
> Non-authoritative answer:
> *** Can't find root-servers.net: No answer
> ```
> 
> however, root-servers.**org**, a.root-servers.net, b.root-servers.net, etc work (see below)
> 
> ```
> Server:         8.8.8.8
> Address:        8.8.8.8#53
> 
> Non-authoritative answer:
> Name:   b.root-servers.net
> Address: 199.9.14.201
> Name:   b.root-servers.net
> Address: 2001:500:200::b
> ```
> 
> Personally it's my opinion to not hardcode values. Allow this to be configurable for the user (and allow them to disable DNS check if they so wish).
> 
> I ran into this very issue here #1164
> 
> @cybertron @qinqon @andreaskaris

The dns probe is auto disabled if it's not working before apply, so we hare safe here.

2023-04-04 10:17 UTC, qinqon commented
This is weird I am sure this was working before, did the change the name ?

2023-04-04 10:18 UTC, qinqon requested changes

2023-04-04 13:26 UTC, k8scoder192 commented
@qinqon 
> 
> The dns probe is auto disabled if it's not working before apply, so we hare safe here.
> 
> As a follow up of this we can add a field to the NMState CR to sepcify the endpoint for the DNS probe.

Thanks for the response and for putting in a field to specify the endpoint in a future release (hopefully soon :)). For this particular PR, I am glad to see the change is now "root-servers.org" that's that correct one

Regarding dns probe auto disabled before apply, I'm **_not_** sure this is working otherwise I wouldn't be seeing dns probe failures (it would be skipped but it's not) see https://github.com/nmstate/kubernetes-nmstate/issues/1164

2023-04-05 08:56 UTC, qinqon commented
> 

Can you retest it ? maybe you where runnig it when `root-server.net` was down or the like, DNS probe like Gateway probe are suppose to be deactivated if not passing before apply:
- https://github.com/nmstate/kubernetes-nmstate/blob/main/pkg/probe/probes.go#L247-L267

You have to see at your logs "WARNING not selecting dns probe"

2023-04-05 08:58 UTC, qinqon commented
/retest

golang hiccup
```
fatal: unable to access 'https://github.com/shazow/go-diff/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443 
```

2023-04-05 08:58 UTC, qinqon commented
/lgtm
/approve

2023-04-05 09:02 UTC, qinqon commented
/retest

```
/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/api/resource/amount.go:23:2: unrecognized import path "gopkg.in/inf.v0": reading https://gopkg.in/inf.v0?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-inf/inf.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
/home/prow/go/pkg/mod/sigs.k8s.io/structured-merge-diff/v4@v4.1.2/value/value.go:26:2: unrecognized import path "gopkg.in/yaml.v2": reading https://gopkg.in/yaml.v2?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/schemapatcher/gen.go:24:2: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

2023-04-05 09:08 UTC, andreaskaris commented
It's root-servers.net, you need to run a NS lookup, not a normal lookup:
~~~
dig ns root-servers.net
~~~

2023-04-05 09:12 UTC, andreaskaris commented
/retest

2023-04-05 09:29 UTC, qinqon commented
/retest

centos 9 stream issues

2023-04-05 09:32 UTC, qinqon commented
> dig ns root-servers.net

Ahh right, it was not a normal lookup, maybe we were having a false possitive here and "dns" probe was always disabled since root-server.net do not exist

/hold

Can you change it back to .net ?

2023-04-05 09:34 UTC, qinqon commented
/hold cancel

2023-04-05 09:48 UTC, andreaskaris commented
/retest-failed

2023-04-05 09:48 UTC, andreaskaris commented
/retest-required

2023-04-05 10:41 UTC, andreaskaris commented
/retest

2023-04-05 13:41 UTC, k8scoder192 commented
> I'm pretty sure it's root-servers.net, you need to run an NS lookup, not a normal lookup:
> 
> 
> dig ns root-servers.net
> 
> 
> > This is weird I am sure this was working before, did the change the name?
> 
> I got no clue why this was working before, but the official domain afaict was always root-servers.net
> 
> 
> $ dig ns root-servers.net
> 
> ; <<>> DiG 9.18.12 <<>> ns root-servers.net
>up root-server.net on 127.0.0.53:53: no such host
>
>
> TRUNCATED OUTPUT
> 
> From what _I_ saw in my tests, the DNS probe is run on startup and when it fails it auto-disabled. I dunno what happens if > stuff is already running and then things go down

--------------------------------------

nslookup **fails** with root-servers.net. It **passes** with root-servers.**org**. Here is my output

```
vanilla@LAPTOP-HGR0D2DR:~$ nslookup root-server.net     <------
;; connection timed out; no servers could be reached



vanilla@LAPTOP-HGR0D2DR:~$ nslookup root-servers.net    <------
Non-authoritative answer:
*** Can't find root-servers.net: No answer


vanilla@LAPTOP-HGR0D2DR:~$ nslookup root-servers.org     <------
Non-authoritative answer:
Name:   root-servers.org
Address: 193.0.11.23
Name:   root-servers.org
Address: 2001:67c:2e8:25::c100:b17
```

**Also** the comment that it will skip DNS lookup if it fails at the start. I know the code is there but it's not working. 
I even completely removed k8s-nmstate from my cluster. Reinstalled v0.74 and it still attempted DNS lookup (obviously with the wrong domain "root-server.net"

@andreaskaris @qinqon

2023-04-05 14:08 UTC, andreaskaris commented
/retest

2023-04-05 14:12 UTC, andreaskaris commented
> Also the comment that it will skip DNS lookup if it fails at the start. I know the code is there but it's not working.
I even completely removed k8s-nmstate from my cluster. Reinstalled v0.74 and it still attempted DNS lookup (obviously with the wrong domain "root-server.net"

Yes but what I saw is that it'll throw an error and then happily continues with the probe disabled.
I had someone in our QE run a verification for something else  and yes there are lots of error messages like this on startup:
~~~
{"level":"error","ts":"2023-04-03T03:24:06.657Z","logger":"probe","msg":"failed checking DNS connectivity","error":"[lookup root-server.net on 10.0.0.2:53: no such host]","stacktrace":"github.com/nmstate/kubernetes-nmstate/pkg/probe.runDNS\n\t/go/src/github.com/openshift/kubernetes-nmstate/pkg/probe/probes.go:239\ngithub.com/nmstate/kubernetes-nmstate/pkg/probe.dnsCondition.func1\n\t/go/src/github.com/openshift/kubernetes-nmstate/pkg/probe/probes.go:206\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:660\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:594\nk8s.io/apimachinery/pkg/util/wait.PollImmediateWithContext\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:526\nk8s.io/apimachinery/pkg/util/wait.PollImmediate\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:512\ngithub.com/nmstate/kubernetes-nmstate/pkg/probe.Select\n\t/go/src/github.com/openshift/kubernetes-nmstate/pkg/probe/probes.go:261\ngithub.com/nmstate/kubernetes-nmstate/pkg/helper.ApplyDesiredState\n\t/go/src/github.com/openshift/kubernetes-nmstate/pkg/helper/client.go:166\ngithub.com/nmstate/kubernetes-nmstate/controllers/handler.(*NodeNetworkConfigurationPolicyReconciler).Reconcile\n\t/go/src/github.com/openshift/kubernetes-nmstate/controllers/handler/nodenetworkconfigurationpolicy_controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/openshift/kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}
~~~

But eventually it shows:
~~~
{"level":"info","ts":"2023-04-03T03:24:06.657Z","logger":"probe","msg":"WARNING not selecting dns probe"}
~~~

And then works. But I tested this with downstream OpenShift so I can't tell if there's a difference upstream

2023-04-05 14:56 UTC, k8scoder192 commented
> 

Agreed, the handler pod, will try a few times then fail DNS and move to ping. The problem is the amount of time until it moves on to the next probe (ping). It's > 5 min. If you are talking about something else, I apologize, I'm specifically referring to the handler pod when looking at the logs. My code looks at event streams and it 5+ min is very long before it sees 
```
status:
  conditions:
    reason: SuccessfullyConfigured
    status: "True"
    type: Available
```

I want to thank you for your feedback and looking into all of this. Much appreciated.

2023-04-05 14:59 UTC, andreaskaris commented
Ah so it's not that it fails, but that it takes a long time. Yeah, then we're on the same page :-) I guess some follow-up is indeed needed to this here, but (if CI actually let me) I just wanted to push a quick fix to the issue at hand

2023-04-06 13:18 UTC, andreaskaris commented
/retest

2023-04-07 16:53 UTC, andreaskaris commented
/retest

2023-04-10 05:46 UTC, qinqon commented
/retest

The centos 9 stream RPM issue has being fixed upstream, but looks like we have e2e test issue at main

2023-04-10 07:07 UTC, merged

2023-04-10 14:14 UTC, k8scoder192 commented
@qinqon @andreaskaris great to see this was merged. Do you know when a release will be created?