Generate events for NMState Handler failures
nmstate/kubernetes-nmstate pull request #1190
Opened 2023-05-29 18:21 UTC by andreaskaris

On top of reporting status via nodenetworkconfigurationenactments, also generate events for failures. These events directly show up in the output of `kubectl describe nodenetworkconfigurationpolicies` and thus provide a standardized way for administrators to understand why a reconciliation failed.

**Is this a BUG FIX or a FEATURE ?**:

/kind enhancement

**What this PR does / why we need it**:

Administrators might not know that they can check their node's status with the nodenetworkconfigurationenactments resource. It's also a non-standard way of reporting the failure of a resource.

**Special notes for your reviewer**:

Consider this a suggestion / brainstorming for how issues with reconciling resources are reported to the users. Would it make sure to use events? If so, should they contain the full error message, or refer to the enactment resource?
I personally really didn't know about the enactment resource until I started working on this PR, and I guess it might be the same for other people using kubernetes-nmstate. Reporting reconciliation issues through the enactment resource seems a bit non-standard to me, and the nodenetworkconfigurationpolicy atm only reports:
~~~
Message:                           x/y nodes failed to configure
~~~

With this change, we'd get something like this:
~~~
$ oc describe nodenetworkconfigurationpolicies
Name:         vlan
Namespace:    
Labels:       <none>
Annotations:  nmstate.io/webhook-mutating-timestamp: 1685383832230481361
API Version:  nmstate.io/v1
Kind:         NodeNetworkConfigurationPolicy
Metadata:
  Creation Timestamp:  2023-05-29T18:10:32Z
  Generation:          1
  Managed Fields:
    API Version:  nmstate.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:desiredState:
          .:
          f:interfaces:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-05-29T18:10:32Z
    API Version:  nmstate.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:lastUnavailableNodeCountUpdate:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2023-05-29T18:12:39Z
  Resource Version:  19056
  UID:               f0df04cb-773e-4b45-8ff5-8341a6db4dbb
Spec:
  Desired State:
    Interfaces:
      ipv4:
        Dhcp:     true
        Enabled:  true
      Name:       eth3.102
      State:      up
      Type:       vlan
      Vlan:
        Base - Iface:  eth3
        Id:            102
Status:
  Conditions:
    Last Heartbeat Time:               2023-05-29T18:12:39Z
    Last Transition Time:              2023-05-29T18:12:39Z
    Reason:                            FailedToConfigure
    Status:                            False
    Type:                              Available
    Last Heartbeat Time:               2023-05-29T18:12:39Z
    Last Transition Time:              2023-05-29T18:12:39Z
    Message:                           1/1 nodes failed to configure
    Reason:                            FailedToConfigure
    Status:                            True
    Type:                              Degraded
    Last Heartbeat Time:               2023-05-29T18:12:39Z
    Last Transition Time:              2023-05-29T18:12:39Z
    Reason:                            ConfigurationProgressing
    Status:                            False
    Type:                              Progressing
  Last Unavailable Node Count Update:  2023-05-29T18:12:39Z
Events:
  Type     Reason           Age    From                    Message
  ----     ------           ----   ----                    -------
  Warning  ReconcileFailed  2m14s  node02.nmstate-handler  error reconciling NodeNetworkConfigurationPolicy on node node02 at desired state apply: "",
 failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' 'Using 'set' is deprecated, use 'apply' instead.
[2023-05-29T18:10:32Z INFO  nmstate::nispor::base_iface] Got unsupported interface type Other("IpTun"): tunl0, ignoring
[2023-05-29T18:10:32Z INFO  nmstate::nispor::show] Got unsupported interface tunl0 type Other("IpTun")
[2023-05-29T18:10:32Z INFO  nmstate::nm::show] Got unsupported interface type ip-tunnel: tunl0, ignoring
[2023-05-29T18:10:32Z INFO  nmstate::query_apply::net_state] Created checkpoint /org/freedesktop/NetworkManager/Checkpoint/8
[2023-05-29T18:10:32Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface cali48c2ba6b6dd type ethernet
[2023-05-29T18:10:32Z INFO  nmstate::nm::query_apply::profile] Creating connection UUID Some("f86eb1bb-198a-4c31-8a27-064e5b10e987"), ID Some("eth3.102"), type Some("vlan") name Some("eth3.102")
[2023-05-29T18:10:33Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:10:33Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:10:33Z INFO  nmstate::nm::query_apply::profile] Will retry activation 2 seconds
[2023-05-29T18:10:35Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:10:35Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:10:35Z INFO  nmstate::nm::query_apply::profile] Will retry activation 4 seconds
[2023-05-29T18:10:39Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:10:39Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:10:39Z INFO  nmstate::nm::query_apply::profile] Will retry activation 8 seconds
[2023-05-29T18:10:47Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:10:47Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:10:47Z INFO  nmstate::nm::query_apply::profile] Will retry activation 16 seconds
[2023-05-29T18:11:03Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:11:03Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:11:03Z INFO  nmstate::nm::query_apply::profile] Will retry activation 32 seconds
[2023-05-29T18:11:35Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:11:35Z INFO  nmstate::query_apply::net_state] Retrying on: Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:11:37Z INFO  nmstate::nm::query_apply::profile] Modifying connection UUID Some("f86eb1bb-198a-4c31-8a27-064e5b10e987"), ID Some("eth3.102"), type Some("vlan") name Some("eth3.102")
[2023-05-29T18:11:37Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:11:37Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for this connection
[2023-05-29T18:11:37Z INFO  nmstate::nm::query_apply::profile] Will retry activation 2 seconds
[2023-05-29T18:11:39Z INFO  nmstate::nm::query_apply::profile] Activating connection f86eb1bb-198a-4c31-8a27-064e5b10e987: eth3.102/vlan
[2023-05-29T18:11:39Z INFO  nmstate::nm::query_apply::profile] Got activation failure Bug: Manager(UnknownDevice): Failed to find a compatible device for t [...]

2023-05-30 05:00 UTC, qinqon requested changes
I really like this approach, can you document it at https://github.com/nmstate/kubernetes-nmstate/blob/main/docs/user-guide/103-troubleshooting.md ?

2023-05-30 05:00 UTC, qinqon commented
/ok-to-test

2023-05-30 09:20 UTC, andreaskaris commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +// nolint: funlen, gocyclo
Coming from https://github.com/golangci/golangci-lint/issues/3098, trying something else now

2023-05-30 12:40 UTC, qinqon commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +// nolint: funlen, gocyclo
I will bump to go 1.20 after merge this

2023-05-30 12:41 UTC, qinqon commented
/lgtm
/approve

2023-05-30 13:22 UTC, andreaskaris commented
/retest-required

2023-05-30 15:35 UTC, qinqon commented
/retest

2023-05-30 17:59 UTC, andreaskaris commented
/retest

2023-05-31 05:35 UTC, qinqon commented
@andreaskaris are the unit test failure related ?

2023-05-31 11:50 UTC, qinqon commented
/lgtm
/approve

2023-05-31 11:51 UTC, merged