e2e: don't require empty starting state for bridge mappings
nmstate/kubernetes-nmstate pull request #1248
Opened 2024-06-14 19:44 UTC by mkowalski

This commit changes the behaviour of the OVN bridge mapping test so that we do not require the initial state to be empty. Thanks to this we make e2e tests working correctly on machines whre OVN is already used and bridges are deployed.

Without this change the test will pass only if no OVN bridge mappings exist on the node. The assumption is quite strong and not really desired.

**Release note**:

```release-note
NONE
```

2024-06-17 05:09 UTC, qinqon requested changes

2024-06-17 05:09 UTC, qinqon commented on test/e2e/handler/nns_ovn.go
> -			Expect(nodeBridgeMappings(node)).To(BeEmpty())
Can we check here the opposite ? 
```golang
NotTo(ContainElement(state.PhysicalNetworks{Name: networkName, Bridge: bridgeName})))
```

2024-06-17 06:57 UTC, mkowalski commented on test/e2e/handler/nns_ovn.go
> -			Expect(nodeBridgeMappings(node)).To(BeEmpty())
Yes, done

2024-06-17 08:51 UTC, mkowalski commented
/test pull-kubernetes-nmstate-e2e-handler-k8s-future

2024-06-17 12:56 UTC, mkowalski commented
/test pull-kubernetes-nmstate-e2e-handler-k8s-future

2024-06-18 05:44 UTC, qinqon commented
/lgtm
/approve

2024-06-18 05:45 UTC, merged