Use jekyll-action-ts
nmstate/kubernetes-nmstate pull request #619
Opened 2020-10-23 10:27 UTC by qinqon

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:
It does not use docker and it's more flexible.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-10-26 13:54 UTC, qinqon commented
/hold

We should have a review CI at GCS bucket or the like.

2020-10-26 14:56 UTC, qinqon commented
/cc @phoracek

2020-10-26 16:23 UTC, phoracek requested changes
Use symlinks or copy for the logo if you need. The repository should keep our logo directory visible, so we know where to find it. It is not meant only as a documentation asset.

Other than that, some nits. I think this is a good start.

2020-10-26 16:23 UTC, phoracek commented on .github/workflows/jekyll.yaml
> +      - name: 📂 setup
That's fancy!

2020-10-26 16:23 UTC, phoracek commented on .github/workflows/jekyll.yaml
> +      - jekyll
We don't need this, do we?

2020-10-26 16:23 UTC, phoracek commented on .github/workflows/jekyll.yaml
> +      # It is highly recommended that you only run this action on push to a
Please drop all boilerplate comments

2020-10-26 16:23 UTC, phoracek commented on docs/_config.yaml
> +title: "The Kubernetes-nmstate project"
"Kubernetes NMState" or "kubernetes-nmstate" would be enough IMO

2020-10-26 16:23 UTC, phoracek commented on docs/_config.yaml
> +name: "The Kubernetes nmstate team"
"Kubernetes NMState" or "kubernetes-nmstate"

2020-10-26 16:23 UTC, phoracek commented on docs/_data/navigation.yaml
> +  - title: Deployment
I'd put deployment first

2020-10-26 16:23 UTC, phoracek commented on docs/index.md
> +title: "The Kubernetes nmstate project"
This is already in the page title. Here it can be "Introduction"

2020-10-27 10:35 UTC, qinqon commented
@phoracek moved the PR to https://github.com/nmstate/kubernetes-nmstate/pull/621 to do it from normal PR user now that we have a proper preview mechanism we don't need to push to a specific branch at origin.

I will address comments there.

2020-10-30 12:43 UTC, closed without merging