Reduce calls to apiserver at nns updates
nmstate/kubernetes-nmstate pull request #664
Opened 2020-12-16 06:15 UTC by qinqon

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
The node controller refresh NNSs every 5 seconds at every Reconcile it
do three things, GET Node, call nmstatectl show and UPDATE NNS, this is
too much of apiserver traffic and end up with big cpu usage. This change
reduce the calls to GET and UPDATE by comparing current network state
with last retrieved network state and if they differ then it do them.

**Special notes for your reviewer**:

**Release note**:

```release-note
Refresh NNS only if needed.
```

2020-12-16 11:44 UTC, qinqon commented
/retest

2020-12-16 14:35 UTC, qinqon commented
/retest 
pull-kubernetes-nmstate-e2e-handler-k8s

2020-12-17 16:00 UTC, phoracek requested changes
Overall it looks good

2020-12-17 16:26 UTC, qinqon commented on pkg/nmstatectl/nmstatectl.go
> +	var re = regexp.MustCompile(` *gc-timer: *[0-9]*\n`)
The alternative is to play around with unstructured json or do complex regexp things, don't know if it's worth it.

2020-12-17 16:27 UTC, qinqon commented on controllers/nodenetworkstate_controller.go
> +	_ = context.Background()
To be honest I copied it from generated controller.

2020-12-17 16:34 UTC, qinqon commented on controllers/nodenetworkstate_controller.go
> +	_ = r.Log.WithValues("nodenetworkstate", request.NamespacedName)
Will use it to initialize logger.

2020-12-18 08:11 UTC, phoracek requested changes

2020-12-18 08:11 UTC, phoracek commented on pkg/helper/client.go
> +		log.Error(err, "failed filtering out interfaces from NodeNetworkState, keeping orignal content, please fix the glob", err)
You don't need err from both sides.

2020-12-18 08:11 UTC, phoracek commented on pkg/nmstatectl/nmstatectl.go
> +		return state, err
Why do we have this early return? we can just return directly

2020-12-18 08:11 UTC, phoracek commented on pkg/helper/client.go
> +		log.Error(err, "failed filtering out interfaces from NodeNetworkState, keeping orignal content, please fix the glob", err)
This would be detected in e2e by simply empty NNS?

2020-12-18 08:11 UTC, phoracek commented on test/e2e/handler/nns_update_timestamp_test.go
> +				timeout := time.Duration(5*3) * time.Second
Can we take the magical number 5 from a constant? And can't we do:

```
3 * theConstant * time.Second?
```

2020-12-18 09:06 UTC, phoracek commented
/lgtm
/approve

2020-12-18 09:56 UTC, merged