Don't create unmatched enactments
nmstate/kubernetes-nmstate pull request #737
Opened 2021-04-30 09:18 UTC by qinqon

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What this PR does / why we need it**:
The enactments that are not matching are created with unmatching
condition, this is a problem at big clusters whey a NNCP with a very
restrictive NodeSelector is applied since it will load the system with a
lot of NNCE saying not matching and this give you no value. This change
just skip creating NNCE if they are not matching.

**Special notes for your reviewer**:

**Release note**:

```release-note
Don't create not matching enactments.
```

2021-04-30 09:18 UTC, qinqon commented
/hold
It's missing deleting previous enactments and some e2e tests.

2021-04-30 10:07 UTC, qinqon commented
/hold cancel

2021-04-30 10:54 UTC, rhrazdil requested changes
Looking great, just TODO mark is left over

2021-04-30 10:54 UTC, rhrazdil commented on controllers/nodenetworkconfigurationpolicy_controller.go
> +		//TODO: Remove enactments if they are not matching now and they were
TODO is done it seems

2021-05-04 15:24 UTC, qinqon commented
/hold 
Enactments are being created then deleted instead of not creating when it's not matching.

2021-05-04 16:23 UTC, qinqon commented
/hold cancel

2021-05-05 05:11 UTC, qinqon commented
/retest 
Handler's locking test is flaky

2021-05-05 08:22 UTC, rhrazdil approved these changes
Thank you
/approve
/lgtm

Adding hold to allow others to review. @qinqon feel free to remove as desired
/hold

2021-05-05 08:29 UTC, qinqon commented
/hold cancel

2021-05-05 08:32 UTC, merged