Add handler E2E tests for static addresses and routes
nmstate/kubernetes-nmstate pull request #863
Opened 2021-11-01 14:32 UTC by yboaron

**Is this a BUG FIX or a FEATURE ?**:

> 
> /kind enhancement

**What this PR does / why we need it**:
This PR adds E2E static (both V4 and V6) addresses and routes tests for handler

2021-11-02 07:24 UTC, yboaron commented
/release-note-none

2021-11-02 09:57 UTC, qinqon commented
/retest

2021-11-02 10:03 UTC, qinqon requested changes
Can you check if those state snippets are not already at https://github.com/nmstate/kubernetes-nmstate/blob/main/test/e2e/handler/states.go ? 

Also don't export the function.

2021-11-03 09:20 UTC, yboaron commented
/retest

2021-11-03 14:37 UTC, qinqon requested changes

2021-11-07 15:35 UTC, yboaron commented on test/e2e/handler/static_addr_and_route_test.go
> +}
Done

2021-11-08 09:48 UTC, qinqon commented
/lgtm
/approve

2021-11-08 09:48 UTC, merged