Fix golangci linters
nmstate/kubernetes-nmstate pull request #995
Opened 2022-02-22 15:25 UTC by tompsota

The warnings from `gocyclo` and `funlen` linters are now resolved.

Signed-off-by: Tomas Psota <tpsota@redhat.com>

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2022-02-23 09:07 UTC, phoracek commented
/retest

2022-02-23 09:11 UTC, phoracek commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +		// Error reading the object - requeue the request.
This comment is not relevant in the scope of the helper function - the re-queue happens on the caller side

2022-02-28 12:51 UTC, tompsota commented
/retest

2022-03-01 11:22 UTC, rhrazdil reviewed
The PR is pretty big, it would if it was spli into at least 2 commits, each delating with a different linter or a specific linter fix.

2022-03-01 11:22 UTC, rhrazdil commented on cmd/handler/main.go
> +	if mainHandler() == 1 {
Could we use a constant?

2022-03-01 11:22 UTC, rhrazdil commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +	err := r.fetchNodeNetworkConfigurationPolicyInstance(instance, &request, &log)
I'm not sure about the motivation for the function.
Also, in go, it's common practice to not use `get/set/fetch/lookup` prefixes in function names.

2022-03-01 11:22 UTC, rhrazdil commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +			err = r.deleteEnactmentForPolicy(request.NamespacedName.Name)
I don't like that this function, that according to its name merely "fetches" a NNCP also deletes something else.

2022-03-01 11:22 UTC, rhrazdil commented on controllers/handler/nodenetworkconfigurationpolicy_controller.go
> +func (r *NodeNetworkConfigurationPolicyReconciler) reconcileEnactmentConditions(
IMO, it doesn't make sense to call this reconcile*
as in k8s , reconcile is a method of a reconciler, that is called by a controller.

2022-03-01 11:22 UTC, rhrazdil commented on pkg/policyconditions/conditions.go
> +		setPolicyStatus(policy, &nmstateMatchingNodes, &enactments, &logger)
I think that abstracting the status logic to a separate function could be a benefit, but can we limit the function to do only that?
And collect/calculate the node statuses outside of this function

2022-03-02 09:53 UTC, tompsota commented
> The PR is pretty big, it would if it was spli into at least 2 commits, each delating with a different linter or a specific linter fix.

Both linters were complaining about approximately the same issues, so we could only split it by files and not by linters, if that's ok

2022-03-09 12:00 UTC, tompsota commented
/retest

2022-03-11 14:32 UTC, rhrazdil requested changes
We need to work a bit on the second commit, I have only minor nits in the third commit.

2022-03-11 14:32 UTC, rhrazdil commented on pkg/policyconditions/conditions.go
> +	logger.Info(
I think we could simply log this information before this function is called. Then we don't need the logger argument.

2022-03-15 14:16 UTC, rhrazdil requested changes
One last nit, looking good otherwise!

2022-03-15 14:16 UTC, rhrazdil commented on cmd/handler/main.go
> +	// Handler runs with host networking so opening ports is problematic
This comment at this scope doesn't make much sense, it should be before the function call.

2022-03-18 10:24 UTC, rhrazdil approved these changes
/lgtm
/approve

2022-03-18 10:45 UTC, merged